events { worker_connections 1024; }

http {
    upstream my_cluster {
        server node1:8000;
        server node2:8000;
        server node3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://my_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}